name: Build and Push Docker Image

on:
  push:
    branches:
      - master  # Trigger the action when code is pushed to the master branch
    tags:
      - '*'    # Trigger the action on all tags

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          kw1k/indexer-tools:latest
          kw1k/indexer-tools:${{ github.ref_name }}
